#!/usr/bin/env node
/* ---------------------------------------------------------------------------
 * Chat flow maps.
 *
 *   node scripts/flow-map.mjs          write docs/chat-flows.md
 *   node scripts/flow-map.mjs --check  exit non-zero if any check fails
 *
 * The traversal itself lives in src/onboarding/flowMap.ts and is shared with
 * the in-app view, so the document, the checker and the screen can't disagree.
 * This file only transpiles that module and renders its output as text.
 * ------------------------------------------------------------------------- */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const ts = require("typescript");

const CACHE = "node_modules/.cache/flowmap";
mkdirSync(CACHE, { recursive: true });

/* Emit both modules side by side so flowMap's `./scripts` import resolves. */
function emit(src, name) {
  const js = ts
    .transpileModule(readFileSync(src, "utf8"), {
      compilerOptions: {
        module: ts.ModuleKind.ESNext,
        target: ts.ScriptTarget.ES2022,
      },
    })
    .outputText.replace(/from "\.\/scripts"/g, 'from "./scripts.mjs"');
  writeFileSync(`${CACHE}/${name}`, js);
}

emit("src/onboarding/scripts.ts", "scripts.mjs");
emit("src/onboarding/flowMap.ts", "flowMap.mjs");

const { analyseAll } = await import(
  pathToFileURL(`${CACHE}/flowMap.mjs`).href
);

const KIND_W = 15;
const out = [
  "# Chat flow maps",
  "",
  "Generated by `npm run flow-map` from `src/onboarding/scripts.ts`.",
  "Do not edit by hand — regenerate instead.",
  "",
  "Also viewable in the app at `/flows/:id`, from the campaign page.",
  "",
  "`!` in the left column marks a step no path reaches.",
  "`◆` marks copy that changes with an earlier answer, with each form listed.",
  "",
];

let failures = 0;

for (const r of analyseAll()) {
  out.push(`## ${r.id} — ${r.source}`);
  out.push("");
  out.push(
    `Reached from ad${r.ads.length === 1 ? "" : "s"} ${
      r.ads.join(", ") || "—"
    } · ${r.reachable} of ${r.total} steps reachable`,
  );
  out.push("");
  out.push("```");
  for (const n of r.nodes) {
    const mark = n.reachable ? " " : "!";
    const num = String(n.index + 1).padStart(2, " ");
    const kind = n.step.kind.toUpperCase().padEnd(KIND_W);
    const label = n.label ? ` [${n.label}]` : "";
    const pause = n.pause ? ` (${n.pause}ms)` : "";
    out.push(`${mark}${num}  ${kind}${label}${pause} ${n.summary}`.trimEnd());
    for (const v of n.variants) {
      const p = v.pause ? ` (${v.pause}ms)` : "";
      out.push(`             ◆ when ${v.when}${p}`);
      out.push(`               "${v.text ?? ""}"`);
    }
    for (const e of n.edges) {
      if (e.exit) out.push("             └─ ends the flow");
      else if (e.broken) out.push(`             └─ BROKEN JUMP on "${e.on}"`);
      else if (e.to == null)
        out.push(`             └─ DEAD END${e.on ? ` on "${e.on}"` : ""}`);
      else if (e.on)
        out.push(
          `             ├─ "${e.on}" ${
            e.to <= n.index ? "loops back to" : "→"
          } step ${e.to + 1}`,
        );
    }
  }
  out.push("```");
  out.push("");
  if (r.problems.length) {
    failures += r.problems.length;
    out.push("**Problems**", "");
    for (const p of r.problems) out.push(`- ${p}`);
  } else {
    out.push("No dead ends, broken jumps or unreachable steps.");
  }
  out.push("");
}

mkdirSync("docs", { recursive: true });
writeFileSync("docs/chat-flows.md", out.join("\n"));
console.log(out.join("\n"));
console.log(failures ? `\n${failures} problem(s) found.` : "\nAll flows check out.");
if (process.argv.includes("--check") && failures) process.exit(1);
